#include "main.h"


#include <stdio.h>
#include <stdlib.h>

#include "images/start_bg.h"
#include "images/end_bg.h"
#include "images/jellyfish.h"
#include "images/trident.h"

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START_BG,
  START,
  SET_GAME,
  PLAY,
  WIN,
  END,
};

// for function later
int catch(int jellyRow, int jellyCol, int tridentRow, int tridentCol);

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Score var
  static int score = 0;
  // Load initial application state
  enum gba_state state = START_BG;

  //Speed of jellyfish
  int speed[] = {-3, -2, -1, 1, 2};
  int deltas = sizeof(speed) / sizeof(speed[0]);

  struct Trident player = {80, 100, 0, 0};

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    prev = curr;
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START_BG:
        waitForVBlank();
        drawFullScreenImageDMA(start_bg); // start screen
        drawString(60, 85, "JELLYFISHING", BLUE); // title name
        drawString(75, 65, "Press ENTER to start", BLACK);
        state = START;
        break;

      case START:
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = SET_GAME;
        }
        break;

      case SET_GAME:
        fillScreenDMA(BLACK);
        score = 0;

        // jellyfish on screen
        curr.nswim = 5;
        for (int i = 0; i < curr.nswim; i++) {
          curr.jellyfishes[i].row = randint(0, HEIGHT);
          curr.jellyfishes[i].col = randint(0, WIDTH);
          curr.jellyfishes[i].rd = speed[randint(0, deltas)];
          curr.jellyfishes[i].cd = speed[randint(0, deltas)];
        }

        state = PLAY;
        break;

      case PLAY:

        // go back to start page if select button pressed (select is delete on keyboard)
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START_BG;
        }

        // press Z to end game, gives different message than when getting all jellyfish
        if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
          state = WIN;
        }

        // arrow keys
        if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
          if (player.col < 220) {
            player.col++;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
          if (player.col > 0) {
            player.col--;
          }
        }
        if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          if (player.row > 0) {
            player.row--;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
          if (player.row < 135) {
            player.row++;
          }
        }

        // screen boundaries
        int screenTop = 0;
        int screenBottom = 159 - 15;
        int screenLeft = 0;
        int screenRight = 239 - 15;

        for (int i = 0; i < curr.nswim; i++) {
          // speed affects movement
          curr.jellyfishes[i].row += curr.jellyfishes[i].rd;
          curr.jellyfishes[i].col += curr.jellyfishes[i].cd;

          // top and bottom
          if (curr.jellyfishes[i].row < screenTop) {
            curr.jellyfishes[i].row = screenTop;
            curr.jellyfishes[i].rd = -curr.jellyfishes[i].rd;
          } else if (curr.jellyfishes[i].row > screenBottom) {
            curr.jellyfishes[i].row = screenBottom;
            curr.jellyfishes[i].rd = -curr.jellyfishes[i].rd;
          }

          // left and right
          if (curr.jellyfishes[i].col < screenLeft) {
            curr.jellyfishes[i].col = screenLeft;
            curr.jellyfishes[i].cd = -curr.jellyfishes[i].cd;
          } else if (curr.jellyfishes[i].col > screenRight) {
            curr.jellyfishes[i].col = screenRight;
            curr.jellyfishes[i].cd = -curr.jellyfishes[i].cd;
          }
        }

        // handling catching jellyfish
        for (int i = 0; i < curr.nswim; i++) {
          if (catch(curr.jellyfishes[i].row, curr.jellyfishes[i].col, player.row, player.col) == 1) {
            curr.jellyfishes[i].row = randint(0, HEIGHT);
            curr.jellyfishes[i].col = randint(0, WIDTH);
            curr.jellyfishes[i].rd = speed[randint(0, deltas)];
            curr.jellyfishes[i].cd = speed[randint(0, deltas)];

            // remove jellyfish from array and update score
            curr.nswim--;
            score++;
          }
        }

        // another way to get to end page
        if (score == 5) {
          state = WIN;
        }

        waitForVBlank();

        // block out previous state
        for (int i = 0; i < prev.nswim; i++) {
          drawRectDMA(prev.jellyfishes[i].row, prev.jellyfishes[i].col, 15, 15, BLACK);
        }

        for (int j = 0; j < curr.nswim; j++) {
          drawImageDMA(curr.jellyfishes[j].row, curr.jellyfishes[j].col, 15, 15, jellyfish);
        }

        // block out previous state
        drawRectDMA(player.prevRow, player.prevCol, 20, 20, BLACK);

        drawImageDMA(player.row, player.col, 20, 20, trident);

        // black box for score
        drawRectDMA(10, 95, 50, 15, BLACK);

        // displayed strings on screen
        char score_display[50];
        sprintf(score_display, "SCORE: %d", score);
        drawString(10, 95, score_display, CYAN);
        drawString(150, 7, "Press Z to end game", LIGHTPURPLE);

        break;

      case WIN:
        waitForVBlank();
        drawFullScreenImageDMA(end_bg); // end background

        char congrats[70];
        if (score == 5) {
          sprintf(congrats, "Wowza! You caught all %d jellyfish!", score);
          drawString(70, 20, congrats, WHITE);
        } else {
          sprintf(congrats, "%d jellyfish... not bad", score);
          drawString(70, 55, congrats, WHITE);
        }
        drawString(85, 25, "Press DELETE to restart the game", YELLOW);
        state = END;
        break;

      case END:
        // press delete to restart game
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START_BG;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}

int catch(int jellyRow, int jellyCol, int tridentRow, int tridentCol) {
  int jellyLeft = jellyCol;
  int jellyRight = jellyCol + 10;
  int jellyTop = jellyRow;
  int jellyBottom = jellyRow + 10;
  int tridentLeft = tridentCol;
  int tridentRight = tridentCol + 15;
  int tridentTop = tridentRow;
  int tridentBottom = tridentRow + 15;
  
  if ((jellyRight >= tridentLeft) && (jellyLeft <= tridentRight) &&
        (jellyBottom >= tridentTop) && (jellyTop <= tridentBottom)) {
		return 1;
	}	

  return 0;
}
